#!/usr/bin/env node
// -*- mode:javascript -*-

"use strict";

var prvl = require('./prevalence.js')();
var path = require('path');
var pdir = process.cwd();

var argv = require('minimist')(process.argv.slice(2),{
    string:['init','fsync'],
    boolean:['debug'],
    int:['fe3','http'],
    defaults:{fsync:'kludge'} });

process.on('SIGINT',function() {
    if (prvl.wrapper)
        prvl.wrapper.close();
    process.exit(1);
});
process.on('SIGQUIT',function() {
    process.exit(1);
});
process.on('SIGHUP',function() {
    if (prvl.wrapper)
        prvl.wrapper.save();
});
process.on('exit',function(code) {
});

require('./compiler.js');       // install chrjs require extension 

var master = argv._[0];

prvl.on('ready',function(syshash) {
    console.log("slaved to: %s",master);
    console.log("opening hash is: %s",syshash);
    // +++ 
});
prvl.replicateFrom(pdir,master);

// +++ if we're running as a slave, have just a prevalence layer
// +++ to become master, close that down that and start a normal server
// +++ against the prevalence store.  Should probably use code from the
// +++ hash store in this new server

// +++ create an engine
// +++  load the world
// +++  journal file:
// +++   line 1 - check against world
// +++   line 2 - code, build map from filenames to hashes
// +++     now load the code into the engine via the map
// +++   rest of lines - add to world
// +++  start adding received commands

// +++ to take this live, create malaya server wrapping
// +++ the prevalence layer and engine
