#!/usr/bin/env node
// -*- mode:javascript -*-
"use strict";

var cmdline = require('../../cmdline.js');
var     idb = require('./idb.js');

cmdline.run({createEngine:function(opts) {
    opts.tag = 'idb';
    if (opts.ports)
        opts.ports.fe3 = 5110;
    return new idb.Engine(opts);
}});

