#!/usr/bin/env node
// -*- mode:javascript -*-
"use strict";

var cmdline = require('malaya/cmdline.js');
var auction = require('./auction.js');

cmdline.run({createEngine:function(opts) {
    opts.tag = 'auction';
    return new auction.Engine(opts);
}});

